In [ ]:
#-----Data Collection------#

In [1]:
import pandas as pd

In [2]:
import numpy

In [3]:
import matplotlib.pyplot as plt

In [4]:
dataset=pd.read_csv('salt_yield_dataset.csv')

In [5]:
dataset=pd.get_dummies(dataset,drop_first=True)

In [6]:
dataset

Pond_Area_m2  Brine_Density_g_cc  Evaporation_Days  Avg_Temperature_C  \
0          2185.4               1.165              15.1               24.2   
1          4778.2               1.208              18.4               20.5   
2          3794.0               1.209              15.3               23.6   
3          3194.0               1.217              12.7               31.7   
4          1202.1               1.225              13.6               28.4   
..            ...                 ...               ...                ...   
295        2850.1               1.203              16.1               37.4   
296        3965.0               1.220              18.8               39.5   
297        1471.2               1.176              36.9               39.4   
298        3303.0               1.177              10.4               35.0   
299         884.1               1.164              12.6               22.6   

     Climate_Temp_Range_C  Solar_Irradiance_W_m2  Salt_Yield_tons  \
0                     7.9                  855.0            1.368   
1                     7.2                  414.8            2.438   
2                     6.1                  413.3            2.396   
3                    10.8                  594.2            2.467   
4                    11.2                  693.2            0.689   
..                    ...                    ...              ...   
295                  14.1                  800.9            2.486   
296                  14.7                  771.7            3.799   
297                  13.2                  678.1            1.219   
298                  15.1                  627.9            2.887   
299                   6.2                  918.0            0.374   

     Crystallization_Method_Continuous  
0                                False  
1                                False  
2                                False  
3                                False  
4                                False  
..                                 ...  
295                              False  
296                               True  
297                              False  
298                              False  
299                              False  

[300 rows x 8 columns]

In [7]:
dataset.columns

Index(['Pond_Area_m2', 'Brine_Density_g_cc', 'Evaporation_Days',
       'Avg_Temperature_C', 'Climate_Temp_Range_C', 'Solar_Irradiance_W_m2',
       'Salt_Yield_tons', 'Crystallization_Method_Continuous'],
      dtype='object')

In [8]:
dataset=dataset.astype(int)

In [9]:
#------Input Output Split------#

In [10]:
independent=dataset[['Pond_Area_m2','Brine_Density_g_cc','Evaporation_Days','Avg_Temperature_C','Climate_Temp_Range_C',
             'Solar_Irradiance_W_m2','Crystallization_Method_Continuous']]

In [12]:
dependent=dataset[['Salt_Yield_tons']]

In [13]:
#------Train Test Split------------#

In [14]:
from sklearn.model_selection import train_test_split

In [15]:
X_train,X_test,y_train,y_test=train_test_split(independent,dependent,test_size=1/3,random_state=0)

In [16]:
#------Standardization of Input and Output---------

In [17]:
from sklearn.preprocessing import StandardScaler

In [18]:
sc=StandardScaler()

In [19]:
X_train=sc.fit_transform(X_train)

In [20]:
X_test=sc.transform(X_test)

In [21]:
scy=StandardScaler()

In [22]:
y_train=scy.fit_transform(y_train)

In [23]:
y_test=scy.transform(y_test)

In [24]:
#------Model Creation-----#

In [25]:
import pickle

In [26]:
preinput=sc.transform([[1000,10,10,10,10,10,0]])

C:\Users\rampr\anaconda3\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(


In [27]:
preinput

array([[-1.35446202,  9.        , -1.6595696 , -3.27739518, -0.094437  ,
        -3.88308705, -0.81649658]])

In [28]:
#------check result before deployment-------

In [29]:
loaded_model=pickle.load(open("final_preboth_svm.sav",'rb'))

In [30]:
result=loaded_model.predict(preinput)

In [31]:
result

array([-1.94655033])

In [32]:
preoutput=scy.inverse_transform([result])

In [33]:
preoutput

array([[-0.68707674]])